import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { RangeRequestsPlugin } from 'workbox-range-requests';
import { clientsClaim } from 'workbox-core';

clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache images with StaleWhileRevalidate strategy
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate({
        cacheName: 'elara-images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache audio files with CacheFirst strategy and RangeRequests support
// This is for songs played online that we want to cache automatically
registerRoute(
    ({ request, url }) => {
        return request.destination === 'audio' ||
            /\.(mp3|m4a|wav|ogg|aac|flac)$/i.test(url.pathname);
    },
    new CacheFirst({
        cacheName: 'elara-audio-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 7 * 24 * 60 * 60, // 7 Days
                purgeOnQuotaError: true,
            }),
            new RangeRequestsPlugin(),
        ],
    })
);

// SPA navigation: serve the app shell (index.html) for all navigations
registerRoute(({ request }) => request.mode === 'navigate', createHandlerBoundToURL('/index.html'));

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
